# defining package and version
{% set name = "libode" %}
{% set version = "0.16.2" %}
{% set soversion = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/odedevs/ode/downloads/ode-{{ version }}.tar.gz
  sha256: b26aebdcb015e2d89720ef48e0cb2e8a3ca77915f89d853893e7cc861f810f22
  patches:
    - add-rt-to-dotpc.patch          # [linux]
    - modify-dotpc-win.patch         # [win]

build:
  number: 4
  skip: true                         # [win and py==27]
  # add libode to the whitelist; it can apparently not be found yet when
  # pyode is built
  missing_dso_whitelist:
    - lib/libode*
    - $RPATH/librt.*                      # [linux]
    - $RPATH/libpthread.*                 # [linux]
    - $RPATH/libc.*                       # [linux]
    - $RPATH/libpython.*                  # [linux]
    - /lib*/librt.*                       # [linux]
    - /lib*/libpthread.*                  # [linux]
    - /lib*/libc.*                        # [linux]
  
requirements:
  build:
    - {{ compiler('cxx') }}          # stage 1, library
    - cmake
    - {{ compiler('c') }}            # stage 2, generate bindings
    - pkg-config
    - m2-patch                       # [win]
    - make                           # [unix]
  host:
    - python {{ PY_VER }}*
    - cython

outputs:
  - name: {{ name }}
    requirements:
      run:
        - pthread-stubs                                              # [unix]
        - libstdcxx-ng                                               # [linux]
        - libgcc-ng                                                  # [linux]
        - libcxx                                                     # [osx]
        - vs2015_runtime                                             # [win]
    run_exports:
      # No ABI docs or ABI Laboratory history, better be conservative
      - {{ pin_subpackage(name, max_pin='x.x.x') }}
    files:
      - lib/libode*                                                  # [unix]
      - lib/pkgconfig/ode.pc                                         # [unix]
      - lib/cmake/ode-{{ soversion }}                                # [unix]
      - bin/ode-config                                               # [unix]
      - Library/lib/ode_double.lib                                   # [win]
      - Library/bin/ode_double.dll                                   # [win]
      - Library/lib/pkgconfig/ode.pc                                 # [win]
      - Library/lib/cmake/ode-{{ soversion }}                        # [win]
      - include/ode
    test:
      commands:
        - test -f $PREFIX/lib/libode${SHLIB_EXT}                     # [unix]
        - test -f $PREFIX/lib/libode${SHLIB_EXT}.{{ soversion }}     # [linux]
        - test -f $PREFIX/lib/libode.{{ soversion }}${SHLIB_EXT}     # [osx]
        - test -d $PREFIX/include/ode                                # [unix]
        - test -f $PREFIX/lib/pkgconfig/ode.pc                       # [unix]
        - test -f $PREFIX/lib/cmake/ode-{{ soversion }}/ode-config.cmake  # [unix]
        - if not exist %PREFIX%\Library\lib\ode_double.lib exit 1    # [win]
        - if not exist %PREFIX%\Library\bin\ode_double.dll exit 1    # [win]
        - if not exist %PREFIX%\Library\lib\pkgconfig\ode.pc exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\ode-{{ soversion }}\\ode-config.cmake  # [win]

  - name: pyode
    requirements:
      run:
        - libode
        - pthread-stubs                                              # [unix]
        - libstdcxx-ng                                               # [linux]
        - libgcc-ng                                                  # [linux]
        - libcxx                                                     # [osx]
        - python {{ PY_VER }}*
    files:
      - lib/python{{ PY_VER }}/site-packages/ode.*                   # [unix]
      - lib/python{{ PY_VER }}/site-packages/Open_Dynamics_Engine*egg-info  # [unix]
      - Lib/site-packages/ode.*.pyd                                  # [win]
      - Lib/site-packages/Open_Dynamics_Engine*egg-info              # [win]
    test:
      imports:
        - ode

about:
  home: https://www.ode.org/
  license: LGPL-2.0 or BSD-4-Clause
  summary: Open Dynamics Engine, dynamics simulation
  license_file:
    - LICENSE.TXT
    - LICENSE-BSD.TXT

extra:
  recipe-maintainers:
    - repagh
