# defining package and version
{% set name = "libode" %}
{% set version = "0.16.5" %}
{% set soversion = "0.16.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/odedevs/ode/downloads/ode-{{ version }}.tar.gz
  sha256: ba875edd164570958795eeaa70f14853bfc34cc9871f8adde8da47e12bd54679
  patches:
    - add-rt-to-dotpc.patch          # [linux]
    - modify-dotpc-win.patch         # [win]
    - fix-pkg-config-setup-py.patch  # [win]
    - distutils-to-setuptools.patch
    - fix_system_ccd_cmake.patch

build:
  number: 0
  run_exports:
    # No ABI docs or ABI Laboratory history, better be conservative
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

  # add libode to the whitelist; it can apparently not be found yet when
  # pyode is built
  missing_dso_whitelist:
    - lib/libode*
    - $RPATH/librt.*                      # [linux]
    - $RPATH/libpthread.*                 # [linux]
    - $RPATH/libc.*                       # [linux]
    - $RPATH/libpython.*                  # [linux]
    - /lib*/librt.*                       # [linux]
    - /lib*/libpthread.*                  # [linux]
    - /lib*/libc.*                        # [linux]
  
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}          # stage 1, library
    - cmake
    - {{ compiler('c') }}            # stage 2, generate bindings
    - {{ stdlib('c') }}
    - pkg-config
    - m2-patch                       # [win]
    - make                           # [unix]
  host:
    - libccd-double
    - python
    - pip
    - cython
    - setuptools

outputs:
  - name: {{ name }}
    build:
      run_exports:
        # No ABI docs or ABI Laboratory history, better be conservative
        - {{ pin_subpackage(name, max_pin='x.x.x') }}
    requirements:
      run:
        - pthread-stubs                                              # [unix]
    files:
      - lib/libode*                                                  # [unix]
      - lib/pkgconfig/ode.pc                                         # [unix]
      - lib/cmake/ode-{{ soversion }}                                # [unix]
      - bin/ode-config                                               # [unix]
      - include/ode                                                  # [unix]
      - Library/lib/ode_double.lib                                   # [win]
      - Library/bin/ode_double.dll                                   # [win]
      - Library/lib/pkgconfig/ode.pc                                 # [win]
      - Library/lib/cmake/ode-{{ soversion }}                        # [win]
      - Library/include/ode                                          # [win]

    test:
      commands:
        - test -f $PREFIX/lib/libode${SHLIB_EXT}                     # [unix]
        - test -f $PREFIX/lib/libode${SHLIB_EXT}.{{ soversion }}     # [linux]
        - test -f $PREFIX/lib/libode.{{ soversion }}${SHLIB_EXT}     # [osx]
        - test -f $PREFIX/include/ode/ode.h                          # [unix]
        - test -f $PREFIX/lib/pkgconfig/ode.pc                       # [unix]
        - test -f $PREFIX/lib/cmake/ode-{{ soversion }}/ode-config.cmake  # [unix]
        - if not exist %PREFIX%\Library\lib\ode_double.lib exit 1    # [win]
        - if not exist %PREFIX%\Library\bin\ode_double.dll exit 1    # [win]
        - if not exist %PREFIX%\Library\lib\pkgconfig\ode.pc exit 1   # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\ode-{{ soversion }}\\ode-config.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\include\\ode\\ode.h exit 1  # [win]
        - cmake-package-check ODE
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}


  - name: pyode
    build:
      run_exports:
        # No ABI docs or ABI Laboratory history, better be conservative
        - {{ pin_subpackage(name, max_pin='x.x.x') }}
    requirements:
      run:
        - libode
    files:
      - lib/python{{ PY_VER }}/site-packages/ode.*                   # [unix]
      - lib/python{{ PY_VER }}/site-packages/Open_Dynamics_Engine*egg-info  # [unix]
      - Lib/site-packages/ode.*.pyd                                  # [win]
      - Lib/site-packages/Open_Dynamics_Engine*egg-info              # [win]
    test:
      imports:
        - ode

about:
  home: https://www.ode.org/
  license: LGPL-2.1-or-later OR BSD-4-Clause
  summary: Open Dynamics Engine, dynamics simulation
  license_file:
    - LICENSE.TXT
    - LICENSE-BSD.TXT

extra:
  recipe-maintainers:
    - repagh
    - traversaro
